### ISSUE TITLE
[Component] 바텀 네비게이션 컴포넌트 - 클릭 이벤트 버그 fix

### ISSUE THREAD

**Issue by Salvation-sub** [gloddy-dev/gloddy-client#27]
https://user-images.githubusercontent.com/52593569/249516108-f6550e58-f5ae-4687-9a8f-4696f30dd425.mov

- 바텀 네비게이션 클릭 이벤트 범위 버그 발생
- 해당 버튼 범위가 아닌곳을 클릭해도 state가 변경되는 이슈 발생

**Comment by guesung** [comment]
![Jun-30-2023 11-32-05](https://github.com/gloddy-dev/gloddy-client/assets/62178788/a649bffb-fd92-4eae-97bc-a79e2f014e89)

저는 잘 작동하는 거 같은데, 아직 동일한 이슈가 발생하나요 ??
