### ISSUE TITLE
[Trouble Shooting] 모임 생성 페이지 Button Disable 문제

### ISSUE THREAD

**Issue by dev-dong-su** [gloddy-dev/gloddy-client#554]
## 문제점
~~_IOS 환경에서 이미지를 업로드할 떄 iCloud에 존재하는 이미지인 경우 다운로드 후 이미지가 업로드 되는데 이 떄 페이지의 hook form이 인식을 하지 못해서 완료 버튼이 활성화 되지 않는 문제._~~

이거도 아님.. -> ~~rn webview 환경에서 페이지가 로드 되자마자 파일 업로드를 시도할 시 이벤트 자체가 씹히는 현상~~

**Comment by jihwan2da** [comment]
ㅋㅋㅋ 화이팅...
